### PR TITLE
Support for Spock framework

### LINKED ISSUE #6: Add support for Spock framework

### PR DESCRIPTION
**Pull request by uKL**
This pull request is based on #5. Please review it first to see the real content. This is to resolve #6

### CODE REVIEW

**Comment by dpreussler** [comment]
cool, will look closer to this when we have the other one done but thanks for doing this :)

**Comment by dpreussler** [comment]
can you rebase so its more easy to see whats new? thanks :)

**Comment by uKL** [comment]
Yup, will do it tomorrow.

**Comment by uKL** [comment]
@dpreussler Ready for review.

**Comment by dpreussler** [comment]
what do you think, would it make sense to have a core module and just the 2 runner in separate directories?

**Comment by uKL** [comment]
That would be consistent.

**Pull request merged**
